version: "3.6"
services:

  elasticsearch:
    image: elasticsearch:5.6.4
    hostname: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data

  postgres:
    image: postgres
    hostname: postgres
    ports:
      - "5432:5432"
      - "6432:6432"
      - "15432:15432"
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ipl
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
